const GET = "GET_DOGS";
const GETDOGS = "GET_DOGSBYNAME";
const GETDOGDB = "GETDOGSDB";
const GETDOGBYID = "GETDOGBYID";
const GET_TEMPERAMENTS = "GETTEMPERAMENTS";
const PAGINAR = "PAGINAR";
const GETBYTEMPERAMENTS = "GETBYTEMPERAMENTS";

module.exports = {
  GETDOGBYID,
  GETDOGS,
  GETDOGDB,
  GET,
  GETBYTEMPERAMENTS,
  GET_TEMPERAMENTS,
  PAGINAR,
};
